### ISSUE TITLE
Question - Attiny13 RX

### ISSUE THREAD

**Issue by gitgaatachal** [pouriap/TinyRF#3]
Does the receiver example code work on Attiny13 MCU?

**Comment by pouriap** [comment]
Unfortunately not.

It needs a relatively big amount of RAM and Flash memory for its buffer functions. 

I've been meaning to try and write a version that works on ATtiny but I'm too busy for the time being. I'm also not so sure if its even possible.

**Comment by gitgaatachal** [comment]
> I've

Oh ok, even I had a doubt after looking into the code and the buffers used. Shall I open a new ticket for RX support for Attiny13? so that when you go over it you can mark the ticket as resolved.

**Comment by pouriap** [comment]
That's a good idea.

Then people who are also interested can also subscribe and be notified.

**Comment by gitgaatachal** [comment]
Hi,
 
I have opened a new ticket
